name: Build VNDS-LOVE
on:
    push:
        branches: ["main"]
        paths-ignore:
            - "*.md"
            - ".github/dependabot.yml"
jobs:
    build:
        permissions:
            contents: write
        name: Build for iOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/checkout@v4
              with:
                  repository: love2d/love
                  path: love2d
                  ref: main
            - uses: actions/checkout@v4
              with:
                  repository: love2d/love-apple-dependencies
                  path: deps
                  ref: main
            - name: Copy dependencies
              run: |
                  cd deps
                  cp -rv iOS/libraries ../love2d/platform/xcode/ios
                  cp -rv shared ../love2d/platform/
                  cd ..
                  cp vnds.xcodeproj love2d/platform/xcode
            - name: Build ipa
              working-directory: ./love2d/platform/xcode
              run: |
                  ls
                  xcodebuild -list -project vnds.xcodeproj
                  xcodebuild -project vnds.xcodeproj clean archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" \
                                           CODE_SIGNING_ALLOWED="NO" -sdk iphoneos -destination 'generic/platform=iOS' -archivePath ./arc -scheme love-ios
                  mkdir Payload
                  cp -rv arc.xcarchive/Products/Applications/VNDS.app Payload
                  zip -r VNDS.ipa Payload
            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ios-build
                  path: |
                      VNDS.ipa
